#!/usr/bin/env bash

set -e # exit on first error

echo "--- running tests ---"
python3 -m unittest
echo ""

echo "--- running mypy ---"
mypy .
echo ""

echo "--- running black ---"
black .
echo ""

echo "--- running ruff ---"
ruff check . && echo "OK"
echo ""
